language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - gradle wrapper
  - chmod +x scripts/run-xvfb
  - scripts/run-xvfb
install: true

addons:
  sonarcloud:
    organization: ylinor-github
  ssh_known_hosts: onaple.fr

script:
  - DISPLAY=:99 ./gradlew sonarqube --stacktrace

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy:
- openssl aes-256-cbc -K $encrypted_182d1a38c631_key -iv $encrypted_182d1a38c631_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/libs/* aventurier@onaple.fr:~/sponge-server-1.12/mods/
  on:
    tags: true
    all_branches: false
